"""
generate_training_data.py
=========================
Generates 800 labeled training examples for RosterIQ intent classification.
Saves to training_data.json — run this once before training.
"""

import json

TRAINING_DATA = {
    "data_query": [
        "How many ROs are currently stuck?",
        "Show me all failed ROs in Kansas",
        "What is the rejection rate for each organization?",
        "List all ROs with IS_STUCK equal to 1",
        "Show me ROs in the PRE_PROCESSING stage",
        "How many ROs failed in the last batch run?",
        "What is the failure rate for Medicare HMO?",
        "Show me all ROs where IS_FAILED is 1",
        "List organizations with rejection rate above 30 percent",
        "How many ROs are in DART generation stage?",
        "Show me all ROs for Aetna in Kansas",
        "What is the health score for each state?",
        "List ROs with DART_GEN_HEALTH marked as Red",
        "How many ROs were received this month?",
        "Show me all ROs with FILE_STATUS_CD 45",
        "What organizations have the highest failure rate?",
        "Show me ROs stuck in ISF generation",
        "How many ROs are in SPS_LOAD stage?",
        "List all ROs with health score below 50",
        "Show me failed ROs for Medicaid FFS",
        "What is the average DART generation duration?",
        "How many ROs have dominant problem in mapping?",
        "Show me all ROs for run number 5",
        "List ROs where SPS_LOAD_HEALTH is Red",
        "How many ROs are anomalies?",
        "Show me all ROs received in January",
        "What is the rejection rate for Commercial PPO?",
        "List ROs with failure status MAPPING_ERROR",
        "How many ROs are in DART review?",
        "Show me all ROs for source system EDI",
        "What is the average ISF generation duration by state?",
        "List organizations with more than 100 stuck ROs",
        "Show me ROs where mapping approval took more than 5 days",
        "How many ROs have health score above 80?",
        "Show me all ROs for Medicare Advantage in Texas",
        "What is the total RO count by LOB?",
        "List all ROs created this week",
        "Show me ROs with pre-processing health marked Yellow",
        "How many ROs failed validation?",
        "Show me all ROs with batch run ID 1234",
        "What organizations are in Kansas?",
        "List ROs with SPS load duration above average",
        "Show me all stuck ROs for United Health",
        "How many ROs are in each pipeline stage?",
        "What is the failure rate by source system?",
        "Show me ROs with DART review duration over 3 days",
        "List all ROs where IS_ANOMALY is 1",
        "How many ROs were processed last month?",
        "Show me all ROs with rejection rate above 50 percent",
        "What is the count of ROs by file status code?",
        "List ROs with missing mapping approval date",
        "Show me all ROs for Cigna",
        "How many ROs completed SPS load successfully?",
        "What is the average health score by organization?",
        "Show me all ROs in Red health status",
        "List ROs that took more than 10 days to process",
        "How many ROs are currently in DART UI validation?",
        "Show me all ROs for Blue Cross Blue Shield",
        "What is the rejection rate trend by month?",
        "List ROs with failure status DART_ERROR",
        "How many ROs have LOB Medicare HMO?",
        "Show me all ROs received but not yet processed",
        "What organizations have zero stuck ROs?",
        "List all ROs with health score between 40 and 60",
        "Show me ROs where ISF generation health is Red",
        "How many ROs are stuck per state?",
        "What is the average pre-processing duration?",
        "Show me all ROs for Humana in Florida",
        "List ROs with DART generation duration above 48 hours",
        "How many ROs failed in pre-processing stage?",
        "Show me all ROs with run number greater than 3",
        "What is the failure rate for each batch run?",
        "List ROs where dominant problem is rejection",
        "Show me all ROs for Molina Healthcare",
        "How many ROs are in Yellow health status?",
        "What is the rejection rate for each LOB?",
        "Show me ROs stuck for more than 7 days",
        "List all ROs with file status 99",
        "How many ROs have IS_FAILED equal to 0?",
        "Show me all ROs processed by user admin",
        "What is the count of ROs by state?",
        "List ROs with SPS load health marked Red",
        "Show me all ROs for WellCare",
        "How many ROs completed successfully on first attempt?",
        "What is the average DART UI validation duration?",
        "Show me all ROs with DART gen health Yellow",
        "List ROs received in the last 30 days",
        "How many ROs have failure status SKIP?",
        "Show me all ROs for Centene Corporation",
        "What organizations have the most anomalies?",
        "List ROs where pre-processing start date is null",
        "How many ROs are stuck in mapping approval?",
        "Show me all ROs with health score below 30",
        "What is the rejection rate for Kansas this month?",
        "List all ROs for LOB Medicaid FFS in Texas",
        "Show me ROs with more than 5 run attempts",
        "How many ROs were created today?",
        "What is the average health score across all states?",
        "Show me all ROs where FAILURE_STATUS is not null",
    ],
    "run_procedure": [
        "Run the triage stuck ros procedure",
        "Execute market health report for all states",
        "Run record quality audit for Kansas",
        "Execute the retry effectiveness analysis",
        "Run triage procedure for Texas",
        "Execute record quality audit for all organizations",
        "Run the market health report",
        "Execute triage stuck ros for Medicare HMO",
        "Run retry effectiveness analysis for last month",
        "Execute the record quality audit now",
        "Run market health report for Kansas and Texas",
        "Execute triage for all stuck ROs",
        "Run the full diagnostic procedure",
        "Execute retry analysis for Medicaid FFS",
        "Run quality audit for United Health",
        "Execute the stuck RO triage procedure immediately",
        "Run market health check for all active markets",
        "Execute record audit for Commercial PPO",
        "Run the standard triage workflow",
        "Execute market health report for Florida",
        "Run retry effectiveness for this batch",
        "Execute the quality audit procedure now",
        "Run triage_stuck_ros for all states",
        "Execute market_health_report procedure",
        "Run record_quality_audit for Aetna",
        "Execute retry_effectiveness_analysis procedure",
        "Run the diagnostic triage now",
        "Execute full market analysis procedure",
        "Run quality check procedure for all orgs",
        "Execute stuck RO analysis workflow",
        "Run the health report procedure",
        "Execute triage for Kansas market",
        "Run audit procedure for this week",
        "Execute the standard diagnostic workflow",
        "Run market health procedure for Texas",
        "Execute triage procedure for Humana",
        "Run the retry analysis procedure",
        "Execute quality audit for all states now",
        "Run triage stuck ros procedure for Medicaid",
        "Execute the full diagnostic suite",
        "Run market health report for all regions",
        "Execute record quality check for Blue Cross",
        "Run the triage workflow for Medicare",
        "Execute retry effectiveness for batch 1234",
        "Run quality audit procedure immediately",
        "Execute the market health diagnostic",
        "Run stuck RO triage for Florida",
        "Execute the audit workflow for all orgs",
        "Run the retry analysis for this month",
        "Execute diagnostic procedure for Kansas market",
        "Run quality audit for Cigna",
        "Execute triage procedure for all anomalies",
        "Run the health check workflow now",
        "Execute market analysis for Medicaid FFS",
        "Run record audit for all Medicare plans",
        "Execute the full triage suite for Texas",
        "Run retry effectiveness analysis now",
        "Execute quality procedure for WellCare",
        "Run the triage stuck ros workflow",
        "Execute market health check for Molina",
        "Run audit procedure for Commercial PPO",
        "Execute the diagnostic workflow for Florida",
        "Run health report procedure for all markets",
        "Execute triage for United Health ROs",
        "Run the record quality procedure",
        "Execute retry analysis workflow for June",
        "Run market health diagnostic for all states",
        "Execute quality audit procedure for Centene",
        "Run the triage procedure for batch run 5",
        "Execute stuck RO analysis for Medicare Advantage",
        "Run quality check for all Medicaid organizations",
        "Execute the health report for Texas market",
        "Run triage workflow for all anomalous ROs",
        "Execute market health report procedure now",
        "Run the standard audit workflow",
        "Execute retry effectiveness for Commercial plans",
        "Run triage stuck ros for all active states",
        "Execute the record audit for Humana",
        "Run the full market health procedure",
        "Execute quality audit for Medicare HMO",
        "Run retry analysis procedure for this quarter",
        "Execute triage procedure for all Red health ROs",
        "Run market health check for Cigna markets",
        "Execute the diagnostic audit now",
        "Run quality procedure for all LOBs",
        "Execute triage for stuck ISF generation ROs",
        "Run the market health report for Medicaid states",
        "Execute retry effectiveness analysis for all orgs",
        "Run audit workflow for this batch run",
        "Execute triage stuck ros immediately",
        "Run the health diagnostic procedure",
        "Execute quality audit for all active markets",
        "Run market health procedure for Medicare Advantage",
        "Execute the triage workflow for Centene",
        "Run record quality audit for all source systems",
        "Execute retry analysis for batch 5678",
        "Run the full diagnostic suite for all states",
        "Execute stuck RO triage for Commercial PPO",
        "Run quality check procedure for Molina Healthcare",
        "Execute market health report for all Medicaid markets",
    ],
    "global_stat": [
        "Give me an overall system health summary",
        "What is the total failure rate across all markets?",
        "How many ROs are in the system right now?",
        "Give me a system wide overview",
        "What is the overall rejection rate?",
        "Show me the total count of all ROs",
        "What is the system health status overall?",
        "Give me aggregate statistics for all markets",
        "What is the overall success rate across all states?",
        "Show me a complete system summary",
        "What are the total failures across all organizations?",
        "Give me the overall pipeline health",
        "What is the system wide anomaly count?",
        "Show me overall metrics for all markets",
        "What is the total number of stuck ROs system wide?",
        "Give me a high level dashboard summary",
        "What is the overall health score across all states?",
        "Show me aggregate failure statistics",
        "What is the total rejection count across the system?",
        "Give me a summary of all pipeline stages",
        "What are the overall system statistics?",
        "Show me the system wide health overview",
        "What is the total success count across all markets?",
        "Give me overall performance metrics",
        "What is the aggregate health score?",
        "Show me system level statistics",
        "What is the overall pipeline performance?",
        "Give me a complete overview of all markets",
        "What are the total counts by health status?",
        "Show me the overall system dashboard",
        "What is the system wide failure summary?",
        "Give me aggregate metrics across all states",
        "What is the total anomaly rate system wide?",
        "Show me overall rejection statistics",
        "What is the system health at a glance?",
        "Give me a bird's eye view of all markets",
        "What are the system wide totals?",
        "Show me the complete health summary",
        "What is the overall stuck RO rate?",
        "Give me total counts for all intent categories",
        "What is the system wide success percentage?",
        "Show me aggregate statistics across all organizations",
        "What are the overall pipeline metrics?",
        "Give me a summary of system performance",
        "What is the total count of anomalies across all markets?",
        "Show me system wide health indicators",
        "What is the overall health of the pipeline?",
        "Give me statistics for the entire system",
        "What are the total failures and successes system wide?",
        "Show me the aggregate rejection rate",
        "What is the overall market performance summary?",
        "Give me a complete system health report",
        "What are the system wide averages?",
        "Show me total RO counts by status",
        "What is the overall pipeline efficiency?",
        "Give me aggregate health scores for all states",
        "What is the system wide stuck rate?",
        "Show me overall failure trends",
        "What are the total counts across all LOBs?",
        "Give me a summary of all pipeline failures",
        "What is the overall system performance today?",
        "Show me aggregate metrics for the entire pipeline",
        "What is the total count of Red health ROs system wide?",
        "Give me overall statistics for all batch runs",
        "What are the system wide rejection trends?",
        "Show me the complete failure summary",
        "What is the overall anomaly rate across all markets?",
        "Give me total counts for all health statuses",
        "What is the system health summary for today?",
        "Show me aggregate data for all organizations",
        "What are the overall trends in pipeline performance?",
        "Give me a high level summary of all failures",
        "What is the total stuck RO count across all states?",
        "Show me system wide performance indicators",
        "What is the overall pipeline health score?",
        "Give me the complete system overview",
        "What are the aggregate statistics for this month?",
        "Show me overall health metrics for all markets",
        "What is the system wide rejection summary?",
        "Give me total anomaly counts for all states",
        "What is the overall success rate for this batch?",
        "Show me the system dashboard",
        "What are the total counts by pipeline stage?",
        "Give me aggregate failure rates across all LOBs",
        "What is the overall health of all markets combined?",
        "Show me system wide stuck RO statistics",
        "What are the overall metrics for this week?",
        "Give me a summary of system health indicators",
        "What is the total failure count system wide?",
        "Show me aggregate performance for all source systems",
        "What is the overall pipeline status?",
        "Give me system level health indicators",
        "What are the system wide success metrics?",
        "Show me overall statistics for all batch runs",
        "What is the total count of ROs by health status?",
        "Give me aggregate rejection rates for all markets",
        "What is the overall anomaly count for this month?",
        "Show me system wide failure statistics",
        "What are the total counts across all states combined?",
    ],
    "memory_recall": [
        "What did we find last time about Kansas?",
        "Show me previous analysis results",
        "What was the rejection rate we found earlier?",
        "Recall what we discussed about Texas",
        "What did the last analysis show?",
        "Show me what we found in the previous session",
        "What was the failure rate from before?",
        "Recall the findings from last time",
        "What did we analyze earlier about Humana?",
        "Show me the previous results for Kansas",
        "What were the findings from the last session?",
        "Recall what we found about stuck ROs before",
        "What did the prior analysis reveal?",
        "Show me the history of Kansas analysis",
        "What was discussed in the last session?",
        "Recall the previous rejection rate findings",
        "What did we find about United Health earlier?",
        "Show me past analysis for Medicare HMO",
        "What were the previous findings for Texas?",
        "Recall what we analyzed about Medicaid FFS",
        "What did the last diagnostic show?",
        "Show me earlier findings about pipeline failures",
        "What was the outcome of the previous analysis?",
        "Recall the findings from our last conversation",
        "What did we discover about Kansas before?",
        "Show me the previous session results",
        "What were the earlier findings for Aetna?",
        "Recall what we found about DART generation issues",
        "What did the prior session reveal about Florida?",
        "Show me past findings for Commercial PPO",
        "What was analyzed before about anomalies?",
        "Recall the previous health score findings",
        "What did we find in the last run?",
        "Show me history of analysis for Cigna",
        "What were the past results for SPS load failures?",
        "Recall what we discussed about mapping errors",
        "What did the previous analysis say about rejections?",
        "Show me earlier results for Medicaid markets",
        "What was found before about ISF generation?",
        "Recall findings from the previous diagnostic",
        "What did we analyze about Blue Cross earlier?",
        "Show me the prior analysis for batch run 5",
        "What were the previous findings about stuck ROs?",
        "Recall what we found about health scores before",
        "What did the last session show about Florida?",
        "Show me past results for Medicare Advantage",
        "What was the prior finding about rejection rates?",
        "Recall what we discussed about pipeline bottlenecks",
        "What did we find earlier about WellCare?",
        "Show me previous analysis of DART review issues",
        "What were the findings from before about Molina?",
        "Recall the earlier diagnostic results",
        "What did we analyze in the previous run?",
        "Show me past findings for all stuck procedures",
        "What was found before about Centene?",
        "Recall what we discussed about health flags",
        "What did the prior analysis show about anomalies?",
        "Show me earlier results for mapping failures",
        "What was analyzed before about Texas markets?",
        "Recall findings from our last analysis session",
        "What did we find about pre-processing issues before?",
        "Show me the history of failure rate analysis",
        "What were the previous results for ISF stage?",
        "Recall what was found about DART UI validation before",
        "What did the last run show for United Health?",
        "Show me prior findings for all Red health markets",
        "What was discussed earlier about batch run failures?",
        "Recall the previous findings for Humana",
        "What did we analyze before about SPS load issues?",
        "Show me past analysis for all Medicare plans",
        "What were the earlier findings about rejection spikes?",
        "Recall what we found about mapping approval delays",
        "What did the previous session say about Kansas?",
        "Show me history of stuck RO analysis",
        "What was found earlier about anomaly patterns?",
        "Recall what we discussed about Commercial PPO before",
        "What did we analyze about DART generation before?",
        "Show me the prior results for all LOBs",
        "What were the findings from the last analysis about Florida?",
        "Recall what was found about pre-processing delays",
        "What did the earlier diagnostic reveal about health scores?",
        "Show me previous findings for all source systems",
        "What was analyzed before about retry effectiveness?",
        "Recall what we found about market health trends",
        "What did the last session show about rejection patterns?",
        "Show me past results for DART review bottlenecks",
        "What were the prior findings for Medicaid markets?",
        "Recall earlier analysis about pipeline stage failures",
        "What did we discuss before about overall system health?",
        "Show me history of anomaly detection results",
        "What was found before about ISF generation delays?",
        "Recall what we analyzed about Kansas rejection rates",
        "What did the previous run show about SPS load health?",
        "Show me prior findings for all anomalous organizations",
        "What were the earlier results for batch processing?",
        "Recall what we found about market health below threshold",
        "What did we analyze before about stuck DART ROs?",
        "Show me the history of procedure execution results",
        "What was discussed earlier about overall failure trends?",
        "Recall findings from the prior session about Texas",
    ],
    "web_search": [
        "Search for recent CMS regulatory updates",
        "Look up compliance rules for high rejection rates",
        "Find recent news about Medicaid roster requirements",
        "Search online for CMS roster submission guidelines",
        "Look up recent changes to healthcare data standards",
        "Find information about HIPAA roster compliance rules",
        "Search for recent Medicaid policy changes",
        "Look up CMS requirements for provider data submission",
        "Find news about Medicare Advantage roster regulations",
        "Search for recent updates to EDI transaction standards",
        "Look up compliance requirements for rejection rates above 30 percent",
        "Find recent regulatory changes affecting provider rosters",
        "Search for CMS guidance on DART processing requirements",
        "Look up recent news about Medicaid enrollment deadlines",
        "Find information about state specific roster requirements",
        "Search online for provider data quality standards",
        "Look up recent CMS bulletins about roster processing",
        "Find news about upcoming healthcare compliance deadlines",
        "Search for regulatory updates affecting ISF generation",
        "Look up compliance rules for SPS load failures",
        "Find recent changes to Medicare provider enrollment",
        "Search for CMS updates on mapping approval requirements",
        "Look up news about Medicaid managed care roster rules",
        "Find information about provider data submission penalties",
        "Search online for recent healthcare data exchange standards",
        "Look up CMS requirements for pre-processing compliance",
        "Find news about state Medicaid roster submission rules",
        "Search for recent updates affecting Commercial PPO rosters",
        "Look up regulatory guidance on rejection rate thresholds",
        "Find recent changes to DART review requirements",
        "Search for compliance standards for provider data quality",
        "Look up recent CMS notices about roster file formats",
        "Find information about upcoming Medicaid policy changes",
        "Search online for healthcare regulatory compliance updates",
        "Look up news about Medicare Advantage enrollment rules",
        "Find recent changes to provider data validation requirements",
        "Search for CMS guidance on handling stuck ROs",
        "Look up compliance requirements for ISF file submissions",
        "Find news about state specific Medicaid data requirements",
        "Search for recent updates to provider roster standards",
        "Look up CMS rules for DART generation failures",
        "Find information about regulatory penalties for data errors",
        "Search online for recent changes to healthcare EDI standards",
        "Look up news about Medicaid FFS roster requirements",
        "Find recent CMS guidance on SPS load compliance",
        "Search for regulatory updates affecting Medicare HMO rosters",
        "Look up compliance rules for pre-processing failures",
        "Find recent news about provider enrollment deadlines",
        "Search for CMS updates on mapping approval standards",
        "Look up information about DART UI validation requirements",
        "Find news about recent changes to Commercial roster rules",
        "Search online for healthcare data quality compliance standards",
        "Look up recent CMS policy changes for Medicaid providers",
        "Find information about state roster submission requirements",
        "Search for recent updates to Medicare provider data rules",
        "Look up compliance guidance for high failure rate markets",
        "Find news about upcoming changes to EDI transaction codes",
        "Search for CMS requirements for anomaly reporting",
        "Look up recent regulatory changes for Medicaid managed care",
        "Find information about provider data submission best practices",
        "Search online for recent HIPAA updates affecting rosters",
        "Look up news about CMS enforcement actions for data errors",
        "Find recent guidance on handling DART generation failures",
        "Search for regulatory updates for Medicare Advantage providers",
        "Look up compliance rules for SPS load processing times",
        "Find news about state Medicaid policy changes this year",
        "Search for CMS guidance on handling rejection spikes",
        "Look up recent updates to provider credentialing requirements",
        "Find information about compliance thresholds for roster quality",
        "Search online for recent healthcare regulatory news",
        "Look up CMS rules for handling mapping approval delays",
        "Find news about upcoming Medicaid roster submission deadlines",
        "Search for regulatory guidance on provider data anomalies",
        "Look up recent changes to Medicare enrollment standards",
        "Find information about state specific DART requirements",
        "Search for CMS updates on ISF generation standards",
        "Look up compliance requirements for pre-processing delays",
        "Find recent news about healthcare data exchange regulations",
        "Search online for CMS provider data quality guidelines",
        "Look up news about Medicaid managed care data requirements",
        "Find recent regulatory updates for Commercial health plans",
        "Search for guidance on handling high rejection rate markets",
        "Look up CMS requirements for SPS load completion times",
        "Find news about recent changes to provider roster formats",
        "Search for compliance updates affecting all healthcare LOBs",
        "Look up recent CMS notices about provider data standards",
        "Find information about regulatory requirements for stuck ROs",
        "Search online for state Medicaid compliance updates",
        "Look up news about Medicare provider data submission rules",
        "Find recent guidance on handling pipeline stage failures",
        "Search for CMS updates on DART review processing times",
        "Look up compliance rules for ISF file validation failures",
        "Find news about upcoming changes to healthcare data standards",
        "Search for regulatory updates affecting all market types",
        "Look up CMS guidance on provider enrollment data quality",
        "Find recent changes to state specific roster requirements",
        "Search online for healthcare compliance best practices",
        "Look up news about Medicaid FFS provider data rules",
        "Find information about CMS penalties for roster data errors",
    ],
    "visualization": [
        "Show me a chart of failure rates by state",
        "Plot the rejection trend over time",
        "Visualize pipeline stage bottlenecks",
        "Create a bar chart of stuck ROs by organization",
        "Show me a graph of health scores by market",
        "Plot failure rates for each LOB",
        "Visualize the rejection rate trend for Kansas",
        "Create a pie chart of ROs by pipeline stage",
        "Show me a line graph of success rates over time",
        "Plot health scores across all states",
        "Visualize stuck RO counts by organization",
        "Create a chart of DART generation durations",
        "Show me a graph of anomaly counts by state",
        "Plot the overall failure trend this month",
        "Visualize rejection rates for each LOB",
        "Create a bar chart of health scores by market",
        "Show me a trend chart of stuck ROs over time",
        "Plot SPS load durations by organization",
        "Visualize market health below threshold",
        "Create a graph of failure rates by source system",
        "Show me a chart of retry effectiveness",
        "Plot pre-processing durations over time",
        "Visualize health score distribution",
        "Create a bar chart of rejections by state",
        "Show me a line chart of overall system health",
        "Plot anomaly rates across all markets",
        "Visualize DART review duration trends",
        "Create a chart of ISF generation failures",
        "Show me a graph of pipeline stage performance",
        "Plot rejection rates for all organizations",
        "Visualize failure counts by LOB",
        "Create a trend chart for market health scores",
        "Show me a bar chart of stuck ROs by state",
        "Plot health score trends for Kansas",
        "Visualize SPS load success rates",
        "Create a chart of mapping approval durations",
        "Show me a graph of overall rejection trends",
        "Plot failure rates across all batch runs",
        "Visualize pre-processing health by organization",
        "Create a bar chart of anomaly counts by market",
        "Show me a trend line for system health",
        "Plot DART generation health by state",
        "Visualize rejection rate spikes over time",
        "Create a chart of ISF generation durations",
        "Show me a graph of stuck RO trends",
        "Plot health scores for all active markets",
        "Visualize overall pipeline performance",
        "Create a bar chart of failures by pipeline stage",
        "Show me a line chart of rejection rates",
        "Plot SPS load duration trends",
        "Visualize market health distribution",
        "Create a chart comparing LOB failure rates",
        "Show me a graph of DART UI validation durations",
        "Plot overall success rates by month",
        "Visualize anomaly distribution across states",
        "Create a trend chart for rejection rates",
        "Show me a bar chart of health scores by LOB",
        "Plot pipeline stage bottlenecks over time",
        "Visualize stuck RO trends by market",
        "Create a chart of overall system health over time",
        "Show me a graph of failure rates by organization",
        "Plot rejection rate distribution",
        "Visualize DART generation performance by state",
        "Create a bar chart of success rates by market",
        "Show me a line graph of anomaly trends",
        "Plot health score distribution across all markets",
        "Visualize pre-processing duration trends",
        "Create a chart of mapping approval health",
        "Show me a graph comparing market performance",
        "Plot ISF generation success rates over time",
        "Visualize failure rate trends by LOB",
        "Create a trend chart for stuck RO counts",
        "Show me a bar chart of rejection rates by source system",
        "Plot overall health score trends",
        "Visualize DART review health distribution",
        "Create a chart of SPS load failures by state",
        "Show me a graph of pipeline health over time",
        "Plot anomaly counts by organization",
        "Visualize market health trends for all states",
        "Create a bar chart of stuck ROs by LOB",
        "Show me a line chart of failure trends",
        "Plot health scores for Medicare markets",
        "Visualize rejection rate distribution by state",
        "Create a trend chart for overall failure rates",
        "Show me a graph of DART generation trends",
        "Plot pipeline performance over the last month",
        "Visualize ISF generation health by organization",
        "Create a chart of pre-processing success rates",
        "Show me a bar chart of anomaly rates by market",
        "Plot SPS load health trends over time",
        "Visualize overall system performance dashboard",
        "Create a line chart of rejection rates by LOB",
        "Show me a graph of stuck ROs over the last week",
        "Plot market health scores for all active states",
        "Visualize failure distribution across pipeline stages",
        "Create a trend chart for DART UI validation durations",
        "Show me a bar chart of health scores by source system",
        "Plot overall rejection trends for this quarter",
        "Visualize mapping approval duration distribution",
        "Create a chart of system health indicators over time",
    ],
    "procedure_update": [
        "Update the health score threshold to 90",
        "Modify the triage procedure to include LOB filter",
        "Change the below threshold value from 85 to 80",
        "Update the rejection rate threshold in the audit procedure",
        "Modify the market health report to include new states",
        "Change the stuck RO definition to include ISF stage",
        "Update the triage procedure parameters",
        "Modify the retry effectiveness analysis filter",
        "Change the health score calculation formula",
        "Update the anomaly detection threshold",
        "Modify the record quality audit for new LOBs",
        "Change the failure rate threshold to 25 percent",
        "Update the market health procedure to add Florida",
        "Modify the triage stuck ros filter criteria",
        "Change the below threshold definition",
        "Update the audit procedure to include new organizations",
        "Modify the health score weights in the procedure",
        "Change the retry analysis lookback period to 90 days",
        "Update the triage procedure for Medicare Advantage",
        "Modify the rejection rate calculation method",
        "Change the anomaly threshold from 2 to 3 standard deviations",
        "Update the market health report filter",
        "Modify the record quality audit threshold",
        "Change the triage procedure to exclude completed ROs",
        "Update the health score threshold from 70 to 80",
        "Modify the retry effectiveness formula",
        "Change the market health report to weekly frequency",
        "Update the stuck RO triage criteria",
        "Modify the audit procedure SQL query",
        "Change the below threshold percentage to 90",
        "Update the anomaly detection procedure",
        "Modify the triage filter to include all LOBs",
        "Change the health score formula in the procedure",
        "Update the rejection rate audit threshold",
        "Modify the market health procedure parameters",
        "Change the triage procedure to include DART stage",
        "Update the quality audit filter for new states",
        "Modify the retry analysis threshold value",
        "Change the anomaly flag criteria in the procedure",
        "Update the triage stuck ros to use new health formula",
        "Modify the record quality audit to add new metrics",
        "Change the market health threshold to 88 percent",
        "Update the procedure to include Medicaid FFS filter",
        "Modify the triage procedure SQL template",
        "Change the failure rate threshold in the audit",
        "Update the health report procedure to add new columns",
        "Modify the stuck RO filter to include mapping stage",
        "Change the retry effectiveness lookback to 60 days",
        "Update the anomaly detection threshold to 95th percentile",
        "Modify the triage procedure for Commercial PPO",
        "Change the market health procedure frequency",
        "Update the record audit to include new failure codes",
        "Modify the health score weights for DART stage",
        "Change the below threshold value to 82 percent",
        "Update the triage filter to exclude test organizations",
        "Modify the retry analysis to include new metrics",
        "Change the anomaly threshold in the quality procedure",
        "Update the market health report SQL query",
        "Modify the triage stuck ros to add new conditions",
        "Change the rejection rate formula in the audit procedure",
        "Update the procedure parameters for new LOB types",
        "Modify the health score calculation to add new stages",
        "Change the triage procedure to include SPS stage",
        "Update the anomaly detection to use rolling average",
        "Modify the quality audit to add rejection rate filter",
        "Change the market health threshold from 85 to 87",
        "Update the retry effectiveness procedure parameters",
        "Modify the triage filter criteria for Medicare markets",
        "Change the health score threshold to 75 percent",
        "Update the audit procedure to use new date range",
        "Modify the stuck RO definition in the triage procedure",
        "Change the below threshold to include retry count",
        "Update the market health SQL to add new joins",
        "Modify the triage procedure for Medicaid markets",
        "Change the anomaly flag to use IQR method",
        "Update the quality audit filter for all source systems",
        "Modify the retry analysis period to last 45 days",
        "Change the triage procedure health score cutoff",
        "Update the market health report to include trends",
        "Modify the procedure to add DART generation filter",
        "Change the rejection threshold in the quality audit",
        "Update the triage stuck ros parameters for new quarter",
        "Modify the health score formula to weight SPS higher",
        "Change the below threshold definition to include LOB",
        "Update the anomaly procedure to flag new patterns",
        "Modify the market health procedure to add new metrics",
        "Change the audit procedure SQL to improve performance",
        "Update the triage filter to include all health statuses",
        "Modify the retry effectiveness to add success rate metric",
        "Change the triage procedure to run on all batch types",
        "Update the quality audit threshold for new compliance rules",
        "Modify the market health report to add new states",
        "Change the health score cutoff from 60 to 65",
        "Update the stuck RO triage to include new stages",
        "Modify the anomaly detection to use new baseline",
        "Change the rejection rate audit to include all LOBs",
        "Update the retry analysis procedure SQL template",
        "Modify the triage procedure to add new filter conditions",
        "Change the market health threshold for Medicaid markets",
        "Update the quality audit to add new failure status codes",
    ],
    "multi_step": [
        "Analyze Kansas market then create a chart of findings",
        "Run triage procedure and then search for fixes online",
        "Show me stuck ROs then plot their duration distribution",
        "Query failed ROs in Texas and then visualize the results",
        "Run the market health report and then show me a chart",
        "Find stuck ROs in Kansas then search for regulatory fixes",
        "Execute triage procedure and then create a bar chart",
        "Show me rejection rates then plot the trend over time",
        "Run quality audit and then visualize the results",
        "Query anomalies in Florida and then show a graph",
        "Get the failure rate then create a trend chart",
        "Run triage stuck ros and then search CMS for solutions",
        "Show me health scores and then plot them by state",
        "Execute market health report then visualize all findings",
        "Find ROs in Red health then search for compliance rules",
        "Query stuck ROs then run the triage procedure on them",
        "Show overall stats and then create a summary chart",
        "Run retry analysis and then plot effectiveness trends",
        "Get rejection rates for Kansas then search for causes online",
        "Execute the audit procedure and then chart the results",
        "Show me failed ROs then visualize failure distribution",
        "Run market health check and then look up CMS guidelines",
        "Query anomaly counts then create a visualization",
        "Get health scores for all states then plot the comparison",
        "Run triage procedure then search for procedure improvements",
        "Show rejection trends and then look up compliance rules",
        "Execute quality audit then create a bar chart of results",
        "Find stuck ROs in DART stage then visualize their durations",
        "Get overall system stats and then plot health trends",
        "Run retry effectiveness analysis then chart the results",
        "Query failure rates by LOB then create a pie chart",
        "Show me Kansas metrics then search for state specific rules",
        "Execute market health report then look up recent CMS updates",
        "Find anomalies in Texas then visualize their distribution",
        "Run the triage procedure then plot stuck RO trends",
        "Get rejection rates by org then create a bar chart",
        "Query failed ROs then search for known failure patterns",
        "Show pipeline bottlenecks then look up optimization strategies",
        "Run quality audit for Kansas then visualize the findings",
        "Get health scores then search for improvement strategies",
        "Execute triage then create a summary visualization",
        "Find high rejection rate orgs then search for causes",
        "Run market health report then plot market comparisons",
        "Query stuck ROs by stage then visualize stage distribution",
        "Get overall failure stats then create a trend chart",
        "Run retry analysis then search for retry best practices",
        "Show me anomaly patterns then look up CMS anomaly guidelines",
        "Execute quality audit then search for compliance updates",
        "Find Red health markets then visualize their metrics",
        "Query failure trends then create a line graph",
        "Run triage procedure for Florida then chart the results",
        "Get rejection rates then search for rejection reduction strategies",
        "Show health score distribution then plot improvements needed",
        "Execute market health check then look up market specific rules",
        "Find stuck ISF generation ROs then visualize durations",
        "Run quality audit then search for audit improvement strategies",
        "Query pipeline performance then create a dashboard chart",
        "Get DART generation stats then search for optimization tips",
        "Show failure rates by LOB then plot LOB comparison chart",
        "Execute triage then search for triage best practices",
        "Find anomalous organizations then visualize their patterns",
        "Run market health report then look up threshold guidelines",
        "Query SPS load failures then create a failure trend chart",
        "Get health scores for Medicaid markets then plot comparison",
        "Show rejection spikes then search for regulatory causes",
        "Execute retry analysis then visualize effectiveness trends",
        "Find stuck ROs in Texas then search for solutions online",
        "Run the quality audit then chart audit findings",
        "Query overall system health then create a summary visual",
        "Get failure rates by state then plot state comparison",
        "Show me pipeline stage performance then search for improvements",
        "Execute triage procedure then look up stuck RO solutions",
        "Find high failure rate markets then visualize market health",
        "Run market health check then search for market improvements",
        "Query rejection rate trends then create a trend visualization",
        "Get anomaly counts by state then plot state anomaly map",
        "Show health indicators then search for health improvement rules",
        "Execute quality audit then visualize quality metrics",
        "Find DART generation bottlenecks then search for fixes",
        "Run triage then create a visualization of triage results",
        "Query stuck RO patterns then search for pattern causes",
        "Get overall stats then plot system performance trends",
        "Show rejection rates for Medicare then search for Medicare rules",
        "Execute market health report then visualize market trends",
        "Find ISF failures then search for ISF compliance requirements",
        "Run retry effectiveness then create a retry comparison chart",
        "Query health score distribution then plot health histogram",
        "Get failure stats for Medicaid then search for Medicaid rules",
        "Show me pipeline health then look up pipeline optimization tips",
        "Execute triage procedure then search for triage improvements",
        "Find stuck mapping ROs then visualize mapping stage issues",
        "Run quality audit then look up quality compliance standards",
        "Query anomaly trends then create an anomaly trend chart",
        "Get rejection patterns then search for pattern explanations",
        "Show market health scores then plot market health comparison",
        "Execute retry analysis then search for retry optimization",
        "Find Red health organizations then visualize their metrics",
        "Run triage then plot the triage results dashboard",
        "Query pipeline failures then search for failure root causes",
        "Get health scores by LOB then create a LOB health chart",
    ],
}


if __name__ == "__main__":
    # Flatten to list of {text, label} dicts
    examples = []
    for intent, queries in TRAINING_DATA.items():
        for query in queries:
            examples.append({"text": query, "label": intent})

    with open("training_data.json", "w") as f:
        json.dump(examples, f, indent=2)

    print(f"[INFO] Generated {len(examples)} training examples")
    for intent, queries in TRAINING_DATA.items():
        print(f"  {intent:<20} {len(queries)} examples")
    print("[INFO] Saved to training_data.json")