import {
    Loader2,
    Search,
    Brain,
    Layout,
    Mic,
    Plus,
    ArrowUp,
    FileText,
    History,
    AlertCircle,
    Play,
    Settings,
    MoreHorizontal,
    Bell,
    Check,
    ChevronDown,
    Globe,
    Database,
    ShieldCheck,
    TrendingUp,
    Activity,
    User,
    LogOut,
    Moon,
    Sun,
} from "lucide-react";

export const Icons = {
    spinner: Loader2,
    search: Search,
    brain: Brain,
    canvas: Layout,
    mic: Mic,
    plus: Plus,
    arrowUp: ArrowUp,
    fileText: FileText,
    history: History,
    alert: AlertCircle,
    play: Play,
    settings: Settings,
    more: MoreHorizontal,
    bell: Bell,
    check: Check,
    chevronDown: ChevronDown,
    globe: Globe,
    database: Database,
    shield: ShieldCheck,
    trending: TrendingUp,
    activity: Activity,
    user: User,
    logout: LogOut,
    moon: Moon,
    sun: Sun,
};
